FROM php:7.4-apache

RUN apt-get update && apt-get install -y libbson-1.0 libmongoc-1.0-0
RUN pecl install mongodb
RUN echo "extension=mongodb.so" > /usr/local/etc/php/conf.d/mongodb.ini

RUN apt-get update && apt-get install -y git unzip

COPY composer.json composer.lock* /var/www/html/

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN composer install --no-scripts --no-autoloader && rm -rf /root/.composer

COPY . /var/www/html

RUN composer dump-autoload --optimize

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80

