version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - "80:80"
    depends_on:
      - mongo

  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
